all:
	cd C02; make -f gcc.makefile
	cd C03; make -f gcc.makefile
	cd C04; make -f gcc.makefile
	cd C05; make -f gcc.makefile
	cd C06; make -f gcc.makefile
	cd C07; make -f gcc.makefile
	cd C08; make -f gcc.makefile
	cd C09; make -f gcc.makefile
	cd C10; make -f gcc.makefile
	cd C11; make -f gcc.makefile
	cd C12; make -f gcc.makefile
	cd C13; make -f gcc.makefile
	cd C14; make -f gcc.makefile
	cd C15; make -f gcc.makefile
	cd C16; make -f gcc.makefile

